### PR TITLE
for the Android Single Sign On app rename the informal german to the formal version

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@nickvergessen do we need a new tag, etc.? I am always a bit lost there…

**Comment by nickvergessen** [comment]
> do we need a new tag, etc.? I am always a bit lost there…

Yes, can do

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/docker-ci/actions/runs/3461223154

**Comment by nickvergessen** [comment]
Fixed https://github.com/nextcloud/Android-SingleSignOn/commit/8b62eba46d90cdb471791795749fcd4729677a26

**Pull request merged**
