### PR TITLE
Android N changes

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Version bumps to 24 versions (libs, image, targets)

Please review @MorrisJobke :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Please review @MorrisJobke :)

I will test drive this once the new CI server is available or @LukasReschke has rebooted the current one 🙈

**Comment by AndyScherzinger** [comment]
Don't we need to reboot anyhow? for the x86 images to actually work?

**Comment by MorrisJobke** [comment]
> Don't we need to reboot anyhow? for the x86 images to actually work?

That's the reason I'm waiting :) (I hope that we will get a new CI server soon and then Lukas don't need to reboot)

**Comment by AndyScherzinger** [comment]
should be fine now. Can you have another look @MorrisJobke? :smiley:

**Pull request merged**
