### PR TITLE
fix(translationtool): Improve regex for vue translation matching

### PR DESCRIPTION
**Pull request by nickvergessen**
- Fix https://github.com/mijorus/rolls/issues/2

Before | After
---|---
grafik | grafik

### CODE REVIEW

**Comment by zorn-v** [comment]
It can be done via "ungreed ?" operator.
Like 
```
/\Wt\s*\(\s*'?([\w.]+)'?,\s*'(.+?)'\s*/
                           here ^
```
But anyway, these regexp are ugly. And more of then it repeated 6 times.
It must to be refactored.

**Comment by tintou** [comment]
I don't really know how to review this, it sounds like it requires a test set somehow, also there is [this project](https://jshmrtn.github.io/vue3-gettext/) that deals with string extractions that might be worth considering :shrug:

**Comment by nickvergessen** [comment]
That's a cool thing, unluckily most apps are not using Vue3 yet.

**Comment by nickvergessen** [comment]
Added some testing as well

**Comment by zorn-v** [comment]
For testing purpose provide
```
t('qwe"asd', "asd)qwe")
t("qwe'asd", someVar)
t(some.var, `It
is
template`)
```

**Pull request merged**
