### PR TITLE
Add translators hint for vue source file and line

### PR DESCRIPTION
**Pull request by nickvergessen**
### Resulting `specialVueFakeDummyForL10nScript.js`
```
// TRANSLATORS src/App.vue:8
t('notifications', 'Notifications');
// TRANSLATORS src/App.vue:8
t('notifications', 'Notifications');
// TRANSLATORS src/App.vue:36
t('notifications', 'Dismiss all notifications');
// TRANSLATORS src/App.vue:37
t('notifications', 'Dismiss all notifications');
// TRANSLATORS src/App.vue:44
t('notifications', 'Requesting browser permissions to show notifications');
// TRANSLATORS src/App.vue:47
t('notifications', 'No notifications');
// TRANSLATORS src/App.vue:220
t('notifications', 'Failed to dismiss all notifications');
// TRANSLATORS src/Components/Action.vue:85
t('notifications', 'Failed to perform action');
// TRANSLATORS src/Components/Notification.vue:9
t('notifications', 'Dismiss');
// TRANSLATORS src/Components/Notification.vue:177
t('notifications', 'seconds ago');
// TRANSLATORS src/Components/Notification.vue:263
t('notifications', 'Failed to dismiss notification');
// TRANSLATORS src/Components/Parameters/File.vue:72
t('notifications', 'in {path}');
// TRANSLATORS src/views/UserSettings.vue:23
t('notifications', 'Notifications');
// TRANSLATORS src/views/UserSettings.vue:25
t('notifications', 'You need to set up your email address before you can receive notification emails.');
// TRANSLATORS src/views/UserSettings.vue:29
t('notifications', 'Send email reminders about unhandled notifications after:');
// TRANSLATORS src/views/UserSettings.vue:69
t('notifications', 'Never');
// TRANSLATORS src/views/UserSettings.vue:70
t('notifications', '1 hour');
// TRANSLATORS src/views/UserSettings.vue:71
t('notifications', '3 hours');
// TRANSLATORS src/views/UserSettings.vue:72
t('notifications', '1 day');
// TRANSLATORS src/views/UserSettings.vue:73
t('notifications', '1 week');
// TRANSLATORS src/views/UserSettings.vue:85
t('notifications', 'Your settings have been updated.');
// TRANSLATORS src/views/UserSettings.vue:87
t('notifications', 'An error occurred while updating your settings.');
```

### Resulting POT segment
```

#. TRANSLATORS src/App.vue:8
#. TRANSLATORS src/views/UserSettings.vue:23
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/lib/Settings/PersonalSection.php:73
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/specialAppInfoFakeDummyForL10nScript.php:2
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/specialVueFakeDummyForL10nScript.js:2
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/specialVueFakeDummyForL10nScript.js:4
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/specialVueFakeDummyForL10nScript.js:26
msgid "Notifications"
msgstr ""


#. TRANSLATORS src/App.vue:44
#: /home/nickv/Nextcloud/23/server/appsbabies/notifications/translationtool/../../notifications/specialVueFakeDummyForL10nScript.js:10
msgid "Requesting browser permissions to show notifications"
msgstr ""
```

### CODE REVIEW

**Comment by rakekniven** [comment]
@nickvergessen Has this improvement been deployed internally at NC? 
Some new changes in vue files at GitHub does not show expected developer notes.

**Comment by nickvergessen** [comment]
The respective person is currently very busy

**Comment by nickvergessen** [comment]
Also we are currently unable to build a new phar file because there is a bug with upstream. We are in contact with them to resolve it and will proceed as soon as we can build again.

**Comment by rakekniven** [comment]
Created an issue to track this.

**Pull request merged**
