### PR TITLE
add pkg-config package needed to build server doc

### PR DESCRIPTION
**Pull request by mgallien**

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by nickvergessen** [comment]
Doesn't seem to work:
https://github.com/nextcloud/documentation/pull/10275

**Comment by mgallien** [comment]
> Doesn't seem to work: [nextcloud/documentation#10275](https://github.com/nextcloud/documentation/pull/10275)

@nickvergessen not the same thing
on one hand you have the python module and on the other hand the native binary
seems like the binary is needed by the python package

**Comment by mgallien** [comment]
@ChristophWurst should I just proceed and we also update the doc about the building process for doc ?

**Comment by ChristophWurst** [comment]
I would highly prefer a solution that not only fixes deployment but also revives docs for local builds and CI

pycairo was found to be a new dependency for the docs. without the package docs can build.

**Comment by mgallien** [comment]
@ChristophWurst is there a way via "requirements.txt" to block an unwanted dependency (I would use this with `apt` `apt install pkg1 pkg2-`)

**Comment by ChristophWurst** [comment]
Follow https://github.com/nextcloud/documentation/issues/10272. I think we need to pin some dependencies.

**Comment by mgallien** [comment]
closing in favor of https://github.com/nextcloud/documentation/issues/10272

**Pull request closed without merging**
