### PR TITLE
Revert "Update documentation's Dockerfile"

### PR DESCRIPTION
**Pull request by juliushaertl**
Reverts nextcloud/docker-ci#59

### CODE REVIEW

**Comment by juliushaertl** [comment]
We need sphinxcontrib-phpdomain 😉

**Comment by skjnldsv** [comment]
But it does not exists on latest! 😕 
https://packages.debian.org/search?searchon=sourcenames&keywords=phpdomain

**Comment by skjnldsv** [comment]
Ok, saw the latest edits! :) 
Nevermind 😉 

https://github.com/nextcloud/docker-ci/blob/b65bf6b2c46a1807e726d1354499f7a5b6ba3224/documentation/Dockerfile#L6

**Comment by MorrisJobke** [comment]
@skjnldsv sorry for not pinging you on it ;)

**Pull request merged**
