### PR TITLE
Add new image for user_saml_shibboleth-php7.3

### PR DESCRIPTION
**Pull request by juliushaertl**
- [x] Build locally
- [x] Test if https://github.com/nextcloud/user_saml/pull/467 passes with it

### CODE REVIEW

**Comment by juliushaertl** [comment]
I'm unable to get the container tested locally as slapd is reporting inside of the container:

```
[integration-tests-master:79] ==> /var/log/dirsrv/slapd-dir/errors <==
[integration-tests-master:80] [09/Oct/2020:09:09:38.480074111 +0000] - ERR - add_new_slapd_process - Unable to start slapd because it is already running as process 7
[integration-tests-master:81] [09/Oct/2020:09:09:38.483456362 +0000] - CRIT - main - Shutting down due to possible conflicts with other slapd processes
```

Strangely there is definitely no slapd process running already. Might be some leftover from running it during the install but I also don't see how that should be different from the php7.2 container.

**Comment by juliushaertl** [comment]
Leaving for further investigation at a later point.

**Comment by juliushaertl** [comment]
@blizzz might have an idea :wink:

**Comment by blizzz** [comment]
you just copied it 1:1 and basically replaced php7.2 with  7.3?

**Comment by juliushaertl** [comment]
Yes, I probably should have stated that ;)

**Comment by blizzz** [comment]
I also build it locally now and run tests against it. 5 of the 8 are failing, but due to timeouts. Is this what you are seeing, too? I have not seen the error message you name, yet it is still a bit fishy.

**Comment by blizzz** [comment]
i created a repo at docker hub and pushed a tag. would let 467 run against it when it is build.

**Comment by blizzz** [comment]
https://github.com/nextcloud/user_saml/pull/467 passes

**Review by blizzz — APPROVED** [review]

**Pull request merged**
