### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by provokateurin**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Rebuild successful https://github.com/nextcloud/docker-ci/actions/runs/5312572215

**Comment by blizzz** [comment]
@provokateurin can we have a new tag, documentation-12, please? cf. https://github.com/nextcloud/docker-ci/pkgs/container/continuous-integration-documentation

**Comment by provokateurin** [comment]
Looks like @nickvergessen already created one: https://github.com/nextcloud/docker-ci/releases/tag/documentation-12
But no CI seems to have built a new image.

**Comment by blizzz** [comment]
Rebuild the release docker doc generator … but generating failed.

```
ERROR: Cannot install -r requirements.txt (line 17), -r requirements.txt (line 20) and docutils==0.19 because these package versions have conflicting dependencies.
```

**Comment by provokateurin** [comment]
https://github.com/nextcloud/documentation/blob/9fca3c34d42647c3efc5c474acb4ee0079449d31/requirements.txt#L5 requires a version that fulfills the version constraints. Not sure what is going on and if it is even related to this change?

**Comment by blizzz** [comment]
Wasn't it the reason, why the image was based on 20.04?

**Comment by provokateurin** [comment]
No idea, but probably nobody bothered to update it? Anyway updating the deps should fix this :crossed_fingers:

**Comment by provokateurin** [comment]
No the description has to be wrong. In 2021 22.04 definitely wasn't available.

**Comment by provokateurin** [comment]
To test this locally, can I just build the image, mount the docs source and try building it?

**Comment by blizzz** [comment]
you've got a point there

**Comment by blizzz** [comment]
> To test this locally, can I just build the image, mount the docs source and try building it?

aye

**Comment by provokateurin** [comment]
Alright, will try to fix this tomorrow

**Comment by provokateurin** [comment]
I didn't have the problems with the python dependencies with the image. Does the image you are using to actually build the documentation add anything? I found out that the image is missing the PHP simplexml extension which breaks the build in a later stage.

**Comment by blizzz** [comment]
It'S the same image with just two scripts added to it. They both start similarly:

```bash
## Fetch sources
git clone --branch "${BRANCH}" --depth=1 https://github.com/nextcloud/documentation.git
cd documentation

## Install
npm install svgexport -g --unsafe-perm=true
pip3 install -r requirements.txt
```

**Comment by provokateurin** [comment]
I did exactly those steps (just verified it again) and it works perfectly. Are you absolutely sure the image is up-to-date?

**Pull request merged**
