### PR TITLE
Build new translationtool.phar

### LINKED ISSUE #331: Deploy improvement for translation of vue files
@nickvergessen Has this improvement been deployed internally at NC? 
Some new changes in vue files at GitHub does not show expected developer notes.

_Originally posted by @rakekniven in https://github.com/nextcloud/docker-ci/issues/321#issuecomment-977170382_

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #331 

@mgallien do you know how/where to deploy this? Is merging to master enough? Or does it need manual pulling somewhere?

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by mgallien — APPROVED** [review]

**Comment by mgallien** [comment]
going to try to remember what is needed
at least a new version of the docker image should be generated

**Comment by mgallien** [comment]
@nickvergessen from my understanding our scripts do not specify a tag when running the docker image to handle server translations (see https://github.com/nextcloud/docker-ci/blob/master/translations/transifexSync.php#L69)

**Comment by nickvergessen** [comment]
Okay, so we merge and tag and it should be fine?

**Comment by mgallien** [comment]
> Okay, so we merge and tag and it should be fine?

from my understanding yes

**Comment by nickvergessen** [comment]
Hopefully I did everything correct?
https://github.com/nextcloud/docker-ci/actions/runs/1654392708
I had no clue what to put in the fields.

**Comment by nickvergessen** [comment]
Should work for apps and seever since Monday

**Comment by nickvergessen** [comment]
Spreed was synced and doesn't have it either. Can you create me a screenshot where the translator hints show normally in transifex?

**Comment by rakekniven** [comment]
Screenshot 2022-01-11 at 17 55 59

https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/155338305?q=developer_notes%3Abutton

**Pull request merged**
