### PR TITLE
Add theming_customcss to transifex

### PR DESCRIPTION
**Pull request by juliushaertl**
For https://github.com/juliushaertl/theming_customcss/issues/15

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by juliushaertl** [comment]
@nickvergessen Since it seems you did the last translation bump with https://github.com/nextcloud/docker-ci/pull/383/files maybe you can help. Is it enough to trigger the image build and do the following parameters look ok?
Screenshot 2022-07-26 at 09 57 02

**Comment by nickvergessen** [comment]
No, that's not correct.

**Comment by nickvergessen** [comment]
Since it involves SSHing into a machine to trigger the first build it's best done by a sysadmin anyway.

**Pull request merged**
