### PR TITLE
Remove outdated stable branch

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Please also deploy it afterwards, thank you :-)

**Comment by MorrisJobke** [comment]
Done.

**Comment by tobiasKaminsky** [comment]
It is really deployed?
It fails with an error that prefs_lock is duplicated, which can be if the values are different, but stable-3.6 and master have the same value, stable-3.5 not.

**Comment by MorrisJobke** [comment]
At least the deploy script said so... let me redeploy.

**Pull request merged**
