### PR TITLE
Add missing tools to documentation for OpenAPI

### PR DESCRIPTION
**Pull request by provokateurin**
Continuing https://github.com/nextcloud/docker-ci/pull/556

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Rebuilt https://github.com/nextcloud/docker-ci/actions/runs/5320098956

**Comment by provokateurin** [comment]
Tag created and CI is running

**Comment by provokateurin** [comment]
Ah I can't trigger it because of not enough permissions. @nickvergessen or @blizzz can you run the workflow?

**Comment by nickvergessen** [comment]
I already did above https://github.com/nextcloud/docker-ci/pull/557#issuecomment-1598317490

**Comment by provokateurin** [comment]
But not with a tag, right?

**Comment by provokateurin** [comment]
https://github.com/nextcloud/docker-ci/pkgs/container/continuous-integration-documentation there is no `documentation-13`

**Comment by nickvergessen** [comment]
it's just the tag latest for all images all the time, at least in the past.

**Comment by blizzz** [comment]
> it's just the tag latest for all images all the time, at least in the recent past.

For release building it'll still be nice to be able to stick to some known working version, in case of emergency. Triggered build for -13 thus.

**Pull request merged**
