### PR TITLE
chore: Drop recipes with unsupported - outdated - PHP versions

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/docker-ci/issues/336

Keep the images but drop the recipes as they no longer used and make the repo very crowded.
(This is git if you need them just look in the git log :wink: )

### CODE REVIEW

**Comment by nickvergessen** [comment]
Kind of yolo, but if others agree, I would be fine

**Review by szaimen — APPROVED** [review]
Fine by me but not sure if we dont need them later possibly?
cc @blizzz

**Comment by susnux** [comment]
> Fine by me but not sure if we don't need them later possibly?

The images are preserved, but the recipes are just dropped form master (see referenced issue we dropped support for those versions with NC18 and NC20).

**Review by blizzz — DISMISSED** [review]
I'd keep 7.1 and above, for the unlikely case someone comes up with something against the oldest possible supported enterprise major.

**Comment by susnux** [comment]
@blizzz those images are still provided just the recipes are removed from master branch.

**Comment by blizzz** [comment]
> @blizzz those images are still provided just the recipes are removed from master branch.

Sure, but it'll be uncomfortable to update or change any of them. It does not hurt having them lying around a little longer. It's unlikely, yet there is not pressing need to remove them early, or is there?

**Comment by susnux** [comment]
@blizzz Ok reverted all php7.1 and 7.2

**Review by blizzz — APPROVED** [review]

**Pull request merged**
