### PR TITLE
Use 0% for iOS

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by marinofaggiana — APPROVED** [review]

**Comment by rakekniven** [comment]
Hello, what is the reason for this change?
Shipping all translations even if they are at 0 percent?

**Comment by nickvergessen** [comment]
Otherwise building the dev version fails because some languages have the translation file but not the info translations yet.
They have to manually be included anyway in the build to be shipped, so the filtering is done there

**Comment by thisIsTheFoxe** [comment]
Technically the problem was just that the files get removed. An alternative would've been to just make sure that for every folder in `iOSClient/Supporting Files/*.lproj` there exists a `InfoPlist.strings` and a `Localizable.strings` file. And if not, create them (they can be empty).

**Comment by rakekniven** [comment]
We just need to attract more translator to have all apps fully translated 😁 
Thanks for your feedback.

**Pull request merged**
