### PR TITLE
Changed case of GitHub username

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by rakekniven** [comment]
Setup looks ok for me. Only thing is the casing.

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
I guess this needs a `translations-app-*` tag and be deployed.
cc @rullzer

**Comment by rakekniven** [comment]
> I guess this needs a `translations-app-*` tag and be deployed.

Can you explain this tag thing for me? Thank you.

**Comment by nickvergessen** [comment]
Well a git tag needs to be created, but since you can't deploy it anyway details don't matter too much

**Comment by nickvergessen** [comment]
@rullzer  can you deploy?

**Comment by rakekniven** [comment]
> Well a git tag needs to be created, but since you can't deploy it anyway details don't matter too much

Well things might change and isn't it good to share knowledge?
For many years now I do a lot regarding translations and it would be nice to share knowledge with me.

**Comment by nickvergessen** [comment]
https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository#18223354

**Comment by nickvergessen** [comment]
Deployed now

**Pull request merged**
