### PR TITLE
Add redis, imagick and apcu to php8.0 image

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
> Should the install list be similar to 7.4? There seem to be some more missing?

I do not know.

I know redis is needed because drone tests are failing because it’s missing.
I added apcu as I know in some cases it speed things up.
I added imagick as it seems expected to have it for tests.

I do not know why xdebug was added to the 7.4 image. Is it needed for some tests?

**Comment by tcitworld** [comment]
It seems to be code coverage.
https://github.com/nextcloud/docker-ci/pull/211

**Comment by come-nc** [comment]
Added xdebug as well

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
Build running at https://github.com/nextcloud/docker-ci/actions/runs/3846411801

**Comment by nickvergessen** [comment]
Follow up in 

#488 and #489

**Comment by come-nc** [comment]
> Build running at https://github.com/nextcloud/docker-ci/actions/runs/3846411801

This was only php8.0, but integration-php8.0 needed to run as well, here:
https://github.com/nextcloud/docker-ci/actions/runs/3882567956

**Pull request merged**
