### PR TITLE
Fix more translations

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by rakekniven** [comment]
With permission of Sendent do you mean access permissions or the license issue which is still open?@nickvergessen

**Comment by nickvergessen** [comment]
the bot is not allowed to push to the repo and don't want to get further error emails every day:
> ERROR: Permission to Sendent-B-V/Sendent-App-for-Nextcloud.git denied to nextcloud-bot.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by rakekniven** [comment]
> ERROR: Permission to Sendent-B-V/Sendent-App-for-Nextcloud.git denied to nextcloud-bot.

Do I have or can get access to this log? It would be helpful whenever it comes to trouble adding new resources or solving sync issues.

**Comment by nickvergessen** [comment]
I get any error send via email from the sync command on our sync service since beginning of the year.
So it is ensured that all other syncs work currently.

**Comment by rakekniven** [comment]
The sync was successful two times. Contacted app author via forum about different issue. See https://help.nextcloud.com/t/translate-commercial-app-sendent-or-not/131115/16
As soon this has been fixed we can try this one as well.

**Pull request merged**
