### PR TITLE
add a docker container for saml integration tests based on php7

### PR DESCRIPTION
**Pull request by schiessle**
add a docker container for saml integration tests based on php7

### CODE REVIEW

**Comment by schiessle** [comment]
@MorrisJobke @rullzer maybe you can have a quick look if everything is OK... As soon as it is merged I can use it, right? Or are there some additional steps necessary?

**Comment by rullzer** [comment]
@schiessle no it needs to be setup on docker hub. I can do that.

**Comment by rullzer** [comment]
https://hub.docker.com/r/nextcloudci/user_saml_shibboleth-php7/builds/bpsd43u9dzlwb3vapghpgma/

It is building now. Lets see if it works...

**Comment by blizzz** [comment]
Next build: https://hub.docker.com/r/nextcloudci/user_saml_shibboleth-php7/builds/bx9jnf2m3ba77j5l9otnvbg/ 🤞

**Comment by blizzz** [comment]
screenshot_20180314_143754

**Pull request merged**
