### PR TITLE
Translate "nextcloud files_confidential"

### PR DESCRIPTION
**Pull request by marcelklehr**

### CODE REVIEW

**Comment by nickvergessen** [comment]
You need to follow the issue template:
https://github.com/nextcloud/docker-ci/issues/new/choose

Are there wrong docs somewhere that lead you to this change directly?

**Comment by marcelklehr** [comment]
> Are there wrong docs somewhere that lead you to this change directly?

Oh.

Well. [Here it says](https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations)

> After sending the invitation, please [open a ticket](https://github.com/nextcloud/docker-ci/issues) requesting access.

But a little later it says:

> For the sync job there is a [configuration file](https://github.com/nextcloud/docker-ci/blob/master/translations/config.json) available in our docker-ci repository. Adding there the repo owner and repo name to the section named app via pull request is enough. Once this change is in one member of the sysadmin team will deploy it to the sync server and the job will then run once a day.

> If you need help then just [open a ticket with the request](https://github.com/nextcloud/docker-ci/issues/new) and we can also guide you through the steps.

So, I thought, I'd save someone the trouble and make the change myself :shrug:

**Comment by nickvergessen** [comment]
All good, not blaming anyone, but the steps are not enough anymore, hence we have the long list in the issue template on the sysadmin side.

Will take care of adjusting the documentation then, thanks for the link!

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Changed in https://github.com/nextcloud/documentation/pull/9751

**Pull request merged**
