### PR TITLE
Add nextcloud-metadata

### PR DESCRIPTION
**Pull request by gino0631**

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rullzer @blizzz I'm not sure if anything else needs to be setup for translations than merging, maybe you know?

**Comment by blizzz** [comment]
neither do I  :speak_no_evil:  

@rullzer or @jancborchardt ?

**Comment by jancborchardt** [comment]
Translations would be @rullzer or @MorrisJobke I assume. :)

**Comment by gino0631** [comment]
@rullzer @MorrisJobke any chances to merge that?

**Comment by juliushaertl** [comment]
@gino0631 Could you rebase and resolve the conflicts?

**Comment by gino0631** [comment]
@juliushaertl done, thanks.

**Comment by juliushaertl** [comment]
@blizzz Does the transifex-sync automatically fetch the updated config from the repo?

**Comment by blizzz** [comment]
i guess, alas I have no hands in that.

**Comment by gino0631** [comment]
Soon we'll see if it works :)

**Comment by gino0631** [comment]
@juliushaertl as I understand, the sync script takes translations from the Nextcloud project on Transifex, but the app is not on the list: https://www.transifex.com/nextcloud/nextcloud/content/ - what are the steps to add it there?

**Comment by gino0631** [comment]
Any ideas why the app's resources are not appearing on Transifex, and what further steps are necessary?
The relevant section of the Developer Manual is [here](https://docs.nextcloud.com/server/17/developer_manual/app/view/l10n.html#adding-translations), if that helps.

**Comment by blizzz** [comment]
i guess we need to bump a tag

**Comment by blizzz** [comment]
@rullzer

**Comment by blizzz** [comment]
@rullzer @gino0631 i just pulled this repo on the transifex sync machine. It might show up tomorrow :crossed_fingers:

**Comment by gino0631** [comment]
@blizzz finally it worked! Thank you all! 🎉

**Comment by gino0631** [comment]
@blizzz it seems that something else is missing - I can't see any commits to the repo :( Nextcloud Bot is added to the Collaborators, but the status is "Awaiting nextcloud-bot’s response", and no commits. Any ideas?

**Comment by gino0631** [comment]
@blizzz as the community on Transifex is already translating the app, I would like to get the last part working - do you have any idea why the translations are not pushed to the repo? Maybe you can check the logs on the sync machine?

**Comment by blizzz** [comment]
I try to find out what's going on

**Comment by blizzz** [comment]
@gino0631 which role does the bot have? Might need to be Admin.

**Comment by rullzer** [comment]
It needs to be able to push directly to the branches.

@gino0631 can you revoke the nextcloud-bot and then add it again?

**Comment by gino0631** [comment]
@rullzer OK, I have cancelled the previous invite, and added nextcloud-bot once again to collaborators.

@blizzz [This article](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) says collaborators do have write access, and there are no other roles.

**Comment by blizzz** [comment]
@rullzer can you accept the invitation on behalf of the bot?

**Comment by blizzz** [comment]
> @blizzz This article says collaborators do have write access, and there are no other roles.

It depends on the repo settings. Basically it must be able to push, could have been that it was due to a protected branch.

**Comment by gino0631** [comment]
As it is said in [the doc](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account), "In a private repository, repository owners can only grant write access to collaborators. Collaborators can't have read-only access to repositories owned by a user account."

I do use branch protection as [recommended](https://docs.nextcloud.com/server/17/developer_manual/app/view/l10n.html#setup-of-the-transifex-sync), but it is only to disable force pushing and prevent branches from being deleted.

At the moment, I think it's because the invitation has to be accepted by someone (currently it is shown as "awaiting nextcloud-bot's response).

**Comment by rullzer** [comment]
No idea why it had to be explicitly accepted.
But in any case.

https://github.com/gino0631/nextcloud-metadata/commit/fe3b85f5a083a87f0fd722091690a2f268963240

**Comment by gino0631** [comment]
@rullzer @blizzz finally! Cool, thanks! 🎉

**Pull request merged**
