### PR TITLE
handle talk-android like files-android regarding branch detection

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@nickvergessen this should bring back translations for stable branches so also the maintenance releases get updated translations. @tobiasKaminsky that there were some issues last time with building a correct image and that you fixed that, so maybe you could cover the build/publish part or maybe we have some dev docs where this is described?

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by nickvergessen** [comment]
Build triggered https://github.com/nextcloud/docker-ci/actions/runs/2318562661

**Comment by nickvergessen** [comment]
Manually synced the app and this commit was done on stable-14.0:
https://github.com/nextcloud/talk-android/commit/0e994c924e1cdc64da2bb9f4c9933cfd0c01114b

please confirm

**Comment by tobiasKaminsky** [comment]
Stable-14 and master 👍

**Comment by AndyScherzinger** [comment]
As discussed, look good 👍

**Pull request merged**
