### PR TITLE
Added "analytics" app to config

### PR DESCRIPTION
**Pull request by rakekniven**
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Comment by rakekniven** [comment]
Please review, merge and deploy it.

**Review by szaimen — APPROVED** [review]

**Review by szaimen — CHANGES_REQUESTED** [review]
blocking, comma is missing

**Comment by szaimen** [comment]
fixed it

**Review by szaimen — APPROVED** [review]
lgtm now

**Comment by rakekniven** [comment]
@szaimen Thanks!

**Pull request merged**
