### PR TITLE
Add gestion to transifex

### PR DESCRIPTION
**Pull request by baimard**
Add gestion to transifex

### CODE REVIEW

**Review by rakekniven — CHANGES_REQUESTED** [review]
See alphabetical ordering. Please adapt.

**Comment by baimard** [comment]
My bad sorry, it's done :)

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
@baimard To add your app to the Transifex sync you have to do more steps.

See https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html?adding-translations#adding-translations

**Comment by baimard** [comment]
@rakekniven yes I need for this part : 

```
Now the GitHub account @nextcloud-bot needs to get write access to your repository. It will run every night and only push commits to the master branch once there is an update to the translation. In general you should enable the protected branches feature at least for the master branch.
```
Even with the documentation I don't understand how to do that ...

**Comment by rakekniven** [comment]
There is a user at GitHub called "nextcloud-bot".

See https://github.com/nextcloud-bot

Please add this user to your repo with write permissions.

**Comment by baimard** [comment]
it's done [image](https://pasteboard.co/KcuKrvZ.png)

is that the good way ?

**Comment by rakekniven** [comment]
Yes, now please do the others steps to prepare your repo.

**Comment by baimard** [comment]
I have done all the steps, yesterday. Is there a problem ?

**Comment by rakekniven** [comment]
Please see my link 
https://github.com/nextcloud/docker-ci/pull/309#issuecomment-885572403

There is a little more to do.

**Comment by baimard** [comment]
> Please see my link
> [#309 (comment)](https://github.com/nextcloud/docker-ci/pull/309#issuecomment-885572403)
> 
> There is a little more to do (tx config, ignore file, folder with gitkeep ... )

I'm sorry, but I have been done all of the steps that are describes in the documentation. See my repository : https://github.com/baimard/gestion (Master branch)

**Comment by baimard** [comment]
any news ?

**Comment by rakekniven** [comment]
Ok, anyone from Nextcloud GmbH need to accept bot invitation to get this started.

**Comment by rakekniven** [comment]
I pinged them minutes ago.

**Comment by baimard** [comment]
Thank you for all :)

**Comment by rakekniven** [comment]
Hello @baimard Can you please check if the invitation you sent for user "nextcloud-bot" has been accepted?

**Comment by baimard** [comment]
The invitation is pending

**Comment by rakekniven** [comment]
> 
> 
> The invitation is pending

Better now?

**Comment by baimard** [comment]
Yes nextcloud bot is q collaborator

**Comment by baimard** [comment]
I can't see my application in https://www.transifex.com/nextcloud/nextcloud/content/

did I have forget a step ?

**Comment by rakekniven** [comment]
Hello @baimard ,

I was writing with people from Nextcloud core a lot.
They are working on it and due to holiday season and one important person was leaving this has not been done.

Sorry for you. Normally this is a small issue as you have prepared everything very well.

**Comment by baimard** [comment]
Thank you for your very fast answer !

The delay is not very important, I was just asking to my self if I have do everything's good.

I hope everything's gonna be alright for everyone :)

**Pull request merged**
