### PR TITLE
add nc health app

### PR DESCRIPTION
**Pull request by datenangebot**

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Ready and deployed. Translations can be made at https://www.transifex.com/nextcloud/nextcloud/health/ (most likely this link only works for admins, but the resource is there with the name `health`).

**Comment by rakekniven** [comment]
@MorrisJobke I disabled the resource at Transifex.
There are many, many unwanted strings there.

Maybe packed js files. 
Will investigate later or tomorrow (important family event today)

**Comment by MorrisJobke** [comment]
> [](https://github.com/datenangebot/health/blob/4e8d109785a08ba0988facd62f8a4d146cfc6d82/.l10nignore#L1)
> Are wildcards not possible here?

Wildcards are not supported. Just remove the `*`. It just checks the whole path of a file if it starts with a line inside `.l10nignore`.

**Comment by MorrisJobke** [comment]
Thanks @rakekniven for the quick feedback and sorry that we didn't noticed it before.

**Comment by MorrisJobke** [comment]
Fix is in the linked PR.

**Comment by rakekniven** [comment]
Reactivated.

**Pull request merged**
