### PR TITLE
Add basic dockerfile with node environment

### PR DESCRIPTION
**Pull request by juliushaertl**
This way we can use a more recent node/npm version for running our builds on CI.

For now I added git and bash, since with that we can easily check if the webpack build is properly committed with something like:

```yaml
  vue-build:
    image: node:lts-alpine
    commands:
      - apk add git bash
      - find js/ -type f -delete
      - npm install
      - npm run build
      - git status
      - bash -c "[[ ! \"`git status --porcelain js/`\" ]] || ( echo 'Uncommited changes in vue build' && exit 1 )"
    when:
      matrix:
        TESTS: vue-build
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
🙌

**Comment by juliushaertl** [comment]
@MorrisJobke Anything else needed to build the image? I pushed a tag afterwards, but that didn't tigger the build.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Anything else needed to build the image? I pushed a tag afterwards, but that didn't tigger the build.

Which tag? Because the tag needs to be configured ;)

**Comment by juliushaertl** [comment]
Ah I thought it will pick up based on the folder name - The folder is node/ and the tag node-1

**Comment by MorrisJobke** [comment]
> Ah I thought it will pick up based on the folder name - The folder is node/ and the tag node-1

This is all manually created ;) docker hub does not support this nice stuff AFAIK (proof me wrong if it does in the meantime ;))

**Comment by MorrisJobke** [comment]
Added here: https://cloud.docker.com/u/nextcloudci/repository/registry-1.docker.io/nextcloudci/node/builds/feb2ab9d-6445-4d46-8331-f4cfd0c473c1

**Comment by MorrisJobke** [comment]
Finally managed to sort out how to configure it in the new UI: https://cloud.docker.com/u/nextcloudci/repository/docker/nextcloudci/node

**Pull request merged**
