### PR TITLE
revert to sys-img-armeabi-v7a-android-24

### PR DESCRIPTION
**Pull request by AndyScherzinger**
cc @MorrisJobke as discussed move back to sys-img-armeabi-v7a-android-24 instead of x86

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I added android-6 as tag ;)

**Comment by AndyScherzinger** [comment]
Nice! Will wait an hour and then try out android-6 pushing it to the app's repo :)

**Comment by MorrisJobke** [comment]
> Nice! Will wait an hour and then try out android-6 pushing it to the app's repo :)

I don't think you need to wait that long: https://hub.docker.com/r/nextcloudci/android/builds/bul5ydfxcnsxjsvm4mdnd4j/

The build already runs for 10 minutes and it usually takes 15 minutes ;)

**Pull request merged**
